name: dnd
version: '${project.version}'
main: dev.blakeismywaifu.dnd.Main
api-version: 1.19
authors: [ BlakeIsMyWaifu ]
permissions:
  dnd.player:
    description: Player
    default: true
commands:
  bind:
    description: Binds a dnd beyond character id to a player
    usage: /bind <id|view|delete> <player>
    permission: dnd.bind
    permission-message: You don't have permission <permission>